# Generated by Django 4.1.3 on 2022-12-03 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados_pagametos', '0001_initial'),
        ('usuario_sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('descricao', models.CharField(max_length=250)),
                ('dados_pagamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados_pagametos.dadospagamentos')),
                ('user_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_sistema.usuariosistema')),
            ],
        ),
    ]
