# Generated by Django 4.1.3 on 2022-12-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_sistema', '0001_initial'),
        ('cliente', '0001_initial'),
        ('status', '0001_initial'),
        ('pedidos', '0002_alter_pedido_nota_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250)),
                ('nota_fiscal', models.IntegerField()),
                ('data_entrega', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status')),
                ('usuario_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_sistema.usuariosistema')),
            ],
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
