# Generated by Django 4.1.3 on 2022-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedidos_delete_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_entrega',
            field=models.DateField(),
        ),
    ]
