# Generated by Django 4.1.3 on 2022-12-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_data_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
