# Generated by Django 4.1.3 on 2022-12-03 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario_sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=250)),
                ('cnpj', models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('usuario_sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_sistema.usuariosistema')),
            ],
        ),
    ]
