# Generated by Django 4.1.3 on 2022-12-03 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(blank=True, max_length=50)),
                ('conta', models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('agencia', models.CharField(blank=True, max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('pix', models.CharField(max_length=50)),
            ],
        ),
    ]
