# Generated by Django 4.1.3 on 2022-12-03 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_pagametos', '0002_alter_dadospagamentos_agencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospagamentos',
            name='agencia',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='dadospagamentos',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dadospagamentos',
            name='conta',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8), django.core.validators.MinLengthValidator(8)]),
        ),
    ]
