# Generated by Django 4.1.3 on 2022-12-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_pagametos', '0003_alter_dadospagamentos_agencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospagamentos',
            name='pix',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
