# Generated by Django 4.1.3 on 2022-12-03 13:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dados_pagametos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('dados_pagamentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados_pagametos.dadospagamentos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
