# Generated by Django 4.1.3 on 2022-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('N', 'Novo'), ('I', 'Iniciado'), ('F', 'Finalizado'), ('E', 'Entrege')], default='N', max_length=1)),
                ('data_criado', models.DateTimeField(auto_now=True)),
                ('data_modificado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
